### ISSUE TITLE
Is 07-multiple-angular-root-elements missing the React app?

### ISSUE THREAD

**Issue by pstephenwille** [juristr/egghead-intro-angular-elements#1]
When I switch to that branch I only get 'my-react-app' with a node_modules, but not the source code.

**Comment by juristr** [comment]
Oh, that's strange. I'll check that later today and fix it. Will let u know & thx for reporting it

**Comment by juristr** [comment]
Hey, I quickly verified it and this is probably a remainder for when you switched branch from https://github.com/juristr/egghead-intro-angular-elements/tree/05-react-meets-angular/my-react-app/src.

The branch you're mentioning isn't actually supposed to contain a react app. It's just that git probably didn't remove the folder when you switch back and forth. In fact if you check the branch online, there is no react folder 🙂
https://github.com/juristr/egghead-intro-angular-elements/tree/07-multiple-angular-root-elements?files=1
